# From: https://github.com/ncipollo/release-action

name: Create Release

on: 
  workflow_dispatch:
    inputs:
        tag:
            description: Release tag to create
            required: true
            type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        name: ${{ github.event.repository.name }} ${{ github.ref_name }}
        skipIfReleaseExists: true
        tag: ${{ github.inputs.tag }}
