# Uses action: https://github.com/ncipollo/release-action

name: Create Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag name
        required: true
        type: string

jobs:
  name: call-release-workflow:
    uses: Andy4495/.github/.github/workflows/arduino-compile-sketches.yml@main
    with:
      tag: ${{ inputs.tag }}

